# Generated by Django 4.2.7 on 2023-11-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(choices=[('A', 'segmentation'), ('B', 'explosion_identify')], max_length=100)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
