# Generated by Django 5.0 on 2023-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="detectPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=64)),
                ("photo", models.ImageField(default="user1.jpg", upload_to="photos")),
            ],
        ),
    ]
